### ISSUE TITLE
Refactor ComponentsParseError into an enum type

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/descriptor-wallet#22]
https://github.com/LNP-BP/descriptor-wallet/blob/c62962df83b089a3c21826d3365f37afe5bcb8d7/hd/src/components.rs#L119-L121

**Comment by senk8** [comment]
Hi, I would like to work on this issue !

**Comment by cryptoquick** [comment]
Heads-up, this enum type and file no longer exists.
