### ISSUE TITLE
Install build error: cannot find modules

### ISSUE THREAD

**Issue by Goosie** [LNP-BP/descriptor-wallet#23]
Following the installation steps:
$ rustup default stable
$ rustup update
$ git clone https://github.com/LNP-BP/descriptor-wallet
$ cd descriptor-wallet
$ cargo install --path . --all-features

I get this errors in the end
  Compiling descriptors v0.6.0 (/home/perry/descriptor-wallet/descriptors)
   Compiling psbt v0.6.0 (/home/perry/descriptor-wallet/psbt)
   Compiling descriptor-wallet v0.6.0 (/home/perry/descriptor-wallet)
error: cannot find derive macro `Parser` in this scope
   --> src/bin/btc-hot.rs:178:10
    |
178 | #[derive(Parser)]
    |          ^^^^^^
    |
note: `Parser` is imported here, but it is only a trait, without a derive macro
   --> src/bin/btc-hot.rs:32:5
    |
32  | use clap::Parser;
    |     ^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
   --> src/bin/btc-hot.rs:180:3
    |
180 | #[clap(
    |   ^^^^
    |
note: `clap` is imported here, but it is a crate, not an attribute
   --> src/bin/btc-hot.rs:16:1
    |
16  | extern crate clap;
    | ^^^^^^^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
   --> src/bin/btc-hot.rs:188:7
    |
188 |     #[clap(subcommand)]
    |       ^^^^
    |
note: `clap` is imported here, but it is a crate, not an attribute
   --> src/bin/btc-hot.rs:16:1
    |
16  | extern crate clap;
    | ^^^^^^^^^^^^^^^^^^

error: cannot find derive macro `Subcommand` in this scope
   --> src/bin/btc-hot.rs:193:10
    |
193 | #[derive(Subcommand)]
    |          ^^^^^^^^^^

error: cannot find derive macro `Parser` in this scope
  --> src/bin/btc-cold.rs:46:10
   |
46 | #[derive(Parser)]
   |          ^^^^^^
   |
note: `Parser` is imported here, but it is only a trait, without a derive macro
  --> src/bin/btc-cold.rs:34:5
   |
34 | use clap::Parser;
   |     ^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
   --> src/bin/btc-hot.rs:210:11
    |
210 |         #[clap(
    |           ^^^^
    |
note: `clap` is imported here, but it is a crate, not an attribute
   --> src/bin/btc-hot.rs:16:1
    |
16  | extern crate clap;
    | ^^^^^^^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
   --> src/bin/btc-hot.rs:231:11
    |
231 |         #[clap(short, long, default_value = "0'")]
    |           ^^^^
    |
note: `clap` is imported here, but it is a crate, not an attribute
   --> src/bin/btc-hot.rs:16:1
    |
16  | extern crate clap;
    | ^^^^^^^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
  --> src/bin/btc-cold.rs:48:3
   |
48 | #[clap(
   |   ^^^^
   |
note: `clap` is imported here, but it is a crate, not an attribute
  --> src/bin/btc-cold.rs:16:1
   |
16 | extern crate clap;
   | ^^^^^^^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
   --> src/bin/btc-hot.rs:235:11
    |
235 |         #[clap(long, group = "network", required_unless_present_any = &["testnet", "signet"])]
    |           ^^^^
    |
note: `clap` is imported here, but it is a crate, not an attribute
   --> src/bin/btc-hot.rs:16:1
    |
16  | extern crate clap;
    | ^^^^^^^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
  --> src/bin/btc-cold.rs:56:7
   |
56 |     #[clap(subcommand)]
   |       ^^^^
   |
note: `clap` is imported here, but it is a crate, not an attribute
  --> src/bin/btc-cold.rs:16:1
   |
16 | extern crate clap;
   | ^^^^^^^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
   --> src/bin/btc-hot.rs:239:11
    |
239 |         #[clap(long, group = "network")]
    |           ^^^^
    |
note: `clap` is imported here, but it is a crate, not an attribute
   --> src/bin/btc-hot.rs:16:1
    |
16  | extern crate clap;
    | ^^^^^^^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
  --> src/bin/btc-cold.rs:63:7
   |
63 |     #[clap(short, long, global = true, default_value("pandora.network"))]
   |       ^^^^
   |
note: `clap` is imported here, but it is a crate, not an attribute
  --> src/bin/btc-cold.rs:16:1
   |
16 | extern crate clap;
   | ^^^^^^^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
   --> src/bin/btc-hot.rs:243:11
    |
243 |         #[clap(long, group = "network")]
    |           ^^^^
    |
note: `clap` is imported here, but it is a crate, not an attribute
   --> src/bin/btc-hot.rs:16:1
    |
16  | extern crate clap;
    | ^^^^^^^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
  --> src/bin/btc-cold.rs:68:7
   |
68 |     #[clap(short = 'p', global = true)]
   |       ^^^^
   |
note: `clap` is imported here, but it is a crate, not an attribute
  --> src/bin/btc-cold.rs:16:1
   |
16 | extern crate clap;
   | ^^^^^^^^^^^^^^^^^^

error: cannot find derive macro `Subcommand` in this scope
  --> src/bin/btc-cold.rs:83:10
   |
83 | #[derive(Subcommand)]
   |          ^^^^^^^^^^

error: cannot find attribute `clap` in this scope
   --> src/bin/btc-cold.rs:102:11
    |
102 |         #[clap(short = 'n', long, default_value = "20")]
    |           ^^^^
    |
note: `clap` is imported here, but it is a crate, not an attribute
   --> src/bin/btc-cold.rs:16:1
    |
16  | extern crate clap;
    | ^^^^^^^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
   --> src/bin/btc-cold.rs:106:11
    |
106 |         #[clap(short, long, default_value = "0")]
    |           ^^^^
    |
note: `clap` is imported here, but it is a crate, not an attribute
   --> src/bin/btc-cold.rs:16:1
    |
16  | extern crate clap;
    | ^^^^^^^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
   --> src/bin/btc-cold.rs:123:11
    |
123 |         #[clap(short = 'n', long, default_value = "20")]
    |           ^^^^
    |
note: `clap` is imported here, but it is a crate, not an attribute
   --> src/bin/btc-cold.rs:16:1
    |
16  | extern crate clap;
    | ^^^^^^^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
   --> src/bin/btc-cold.rs:127:11
    |
127 |         #[clap(short, long, default_value = "0")]
    |           ^^^^
    |
note: `clap` is imported here, but it is a crate, not an attribute
   --> src/bin/btc-cold.rs:16:1
    |
16  | extern crate clap;
    | ^^^^^^^^^^^^^^^^^^

warning: unused `#[macro_use]` import
  --> src/bin/btc-hot.rs:15:1
   |
15 | #[macro_use]
   | ^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

error: cannot find attribute `clap` in this scope
   --> src/bin/btc-cold.rs:131:11
    |
131 |         #[clap(short = 'c', long = "change")]
    |           ^^^^
    |
note: `clap` is imported here, but it is a crate, not an attribute
   --> src/bin/btc-cold.rs:16:1
    |
16  | extern crate clap;
    | ^^^^^^^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
   --> src/bin/btc-cold.rs:146:11
    |
146 |         #[clap(short, long, default_value = "none")]
    |           ^^^^
    |
note: `clap` is imported here, but it is a crate, not an attribute
   --> src/bin/btc-cold.rs:16:1
    |
16  | extern crate clap;
    | ^^^^^^^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
   --> src/bin/btc-cold.rs:155:11
    |
155 |         #[clap(
    |           ^^^^
    |
note: `clap` is imported here, but it is a crate, not an attribute
   --> src/bin/btc-cold.rs:16:1
    |
16  | extern crate clap;
    | ^^^^^^^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
   --> src/bin/btc-cold.rs:201:11
    |
201 |         #[clap(short, long = "output", required = true)]
    |           ^^^^
    |
note: `clap` is imported here, but it is a crate, not an attribute
   --> src/bin/btc-cold.rs:16:1
    |
16  | extern crate clap;
    | ^^^^^^^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
   --> src/bin/btc-cold.rs:205:11
    |
205 |         #[clap(short, long, default_value = "0")]
    |           ^^^^
    |
note: `clap` is imported here, but it is a crate, not an attribute
   --> src/bin/btc-cold.rs:16:1
    |
16  | extern crate clap;
    | ^^^^^^^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
   --> src/bin/btc-cold.rs:224:11
    |
224 |         #[clap(short = 'o', long = "output")]
    |           ^^^^
    |
note: `clap` is imported here, but it is a crate, not an attribute
   --> src/bin/btc-cold.rs:16:1
    |
16  | extern crate clap;
    | ^^^^^^^^^^^^^^^^^^

error: cannot find attribute `clap` in this scope
   --> src/bin/btc-cold.rs:229:11
    |
229 |         #[clap(long)]
    |           ^^^^
    |
note: `clap` is imported here, but it is a crate, not an attribute
   --> src/bin/btc-cold.rs:16:1
    |
16  | extern crate clap;
    | ^^^^^^^^^^^^^^^^^^

warning: unused `#[macro_use]` import
  --> src/bin/btc-cold.rs:15:1
   |
15 | #[macro_use]
   | ^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

error[E0599]: no function or associated item named `parse` found for struct `Args` in the current scope
   --> src/bin/btc-hot.rs:477:22
    |
186 | pub struct Args {
    | --------------- function or associated item `parse` not found for this
...
477 |     let args = Args::parse();
    |                      ^^^^^ function or associated item not found in `Args`
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following traits define an item `parse`, perhaps you need to implement one of them:
            candidate #1: `Parser`
            candidate #2: `syn::parse_quote::ParseQuote`
            candidate #3: `syn::parse_macro_input::ParseMacroInput`
            candidate #4: `syn::parse::Parse`
            candidate #5: `syn::parse::Parser`

error[E0599]: no function or associated item named `parse` found for struct `Args` in the current scope
   --> src/bin/btc-cold.rs:646:22
    |
54  | pub struct Args {
    | --------------- function or associated item `parse` not found for this
...
646 |     let args = Args::parse();
    |                      ^^^^^ function or associated item not found in `Args`
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following traits define an item `parse`, perhaps you need to implement one of them:
            candidate #1: `Parser`
            candidate #2: `syn::parse_quote::ParseQuote`
            candidate #3: `syn::parse_macro_input::ParseMacroInput`
            candidate #4: `syn::parse::Parse`
            candidate #5: `syn::parse::Parser`

For more information about this error, try `rustc --explain E0599`.
warning: `descriptor-wallet` (bin "btc-hot") generated 1 warning
error: could not compile `descriptor-wallet` due to 10 previous errors; 1 warning emitted
warning: build failed, waiting for other jobs to finish...
warning: `descriptor-wallet` (bin "btc-cold") generated 1 warning
error: failed to compile `descriptor-wallet v0.6.0 (/home/perry/descriptor-wallet)`, intermediate artifacts can be found at `/home/perry/descriptor-wallet/target`

Caused by:
  build failed

**Comment by Goosie** [comment]
When I do just:
$ cargo build
It will compile.

**Comment by Goosie** [comment]
I found to changes to solve this issue, do know of they are correct:

1. Change line 47 in Cargo.toml (add :features = [ "derive" ] : 
clap = { version = "3.0.0-beta.5", optional = true }
into:
clap = { version = "3.0.0-beta.5", optional = true, features = [ "derive" ] }

2. Add --locked in the terminal command:
cargo install --locked --path . --all-features
instead of:
cargo install --path . --all-features

Now it's compiling

**Comment by dr-orlovsky** [comment]
Thanks for reporting, I've included the fix in the master already.

Clap has updated version from beta.5 to rc.1 breaking back compatibility and that caused the problem :(

**Comment by Goosie** [comment]
Tested, unfortunately I run into an other error:  no method named `long_about` found for struct `Arg`  Will create a new issue for this.

**Comment by dr-orlovsky** [comment]
Pre-release clap v3 is a pain: each time they do a minor version it just breaks all the crates... and they keep doing for two years for now which took them to get from `v0.3.0-beta.1 to `v0.3.0-rc.1` :(

**Comment by dr-orlovsky** [comment]
Oh, it's already `-rc.4` for now, they do a new version each day breaking more and more stuff in a random manner :(

**Comment by dr-orlovsky** [comment]
Ok, I fixed with the last updated commit + added `--locked` to README install instruction to stop this from breaking with each new `clap` pre-release
