### ISSUE TITLE
Install build error:  no method named `long_about` found for struct `Arg` 

### ISSUE THREAD

**Issue by Goosie** [LNP-BP/descriptor-wallet#24]
After following the install steps as written in the Readme
I run into the error:
perry@Desktop:~/repos/descriptor-wallet$ cargo install --path . --all-features
  Installing descriptor-wallet v0.6.0 (/home/perry/repos/descriptor-wallet)
    Updating crates.io index
    Updating git repository `https://github.com/LNP-BP/rust-bitcoin`
    Updating git repository `https://github.com/LNP-BP/client_side_validation`
    Updating git repository `https://github.com/LNP-BP/rust-electrum-client`
    Updating git repository `https://github.com/LNP-BP/lnp-core`
    Updating git repository `https://github.com/LNP-BP/rust-miniscript`
   Compiling descriptor-wallet v0.6.0 (/home/perry/repos/descriptor-wallet)
error[E0599]: no method named `long_about` found for struct `Arg` in the current scope
   --> src/bin/btc-hot.rs:213:13
    |
213 |             long_about = "Possible values are:
    |             ^^^^^^^^^^ method not found in `Arg<'_>`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `descriptor-wallet` due to previous error
warning: build failed, waiting for other jobs to finish...
error[E0599]: no method named `long_about` found for struct `Arg` in the current scope
   --> src/bin/btc-cold.rs:159:13
    |
159 |             long_about = "\
    |             ^^^^^^^^^^ method not found in `Arg<'_>`

error: failed to compile `descriptor-wallet v0.6.0 (/home/perry/repos/descriptor-wallet)`, intermediate artifacts can be found at `/home/perry/repos/descriptor-wallet/target`

Caused by:
  build failed

**Comment by dr-orlovsky** [comment]
Ok, I fixed with the last updated commit + added `--locked` to README install instruction to stop this from breaking with each new `clap` pre-release

**Comment by Goosie** [comment]
It's compiling now, following the latest compile instructions.
