### ISSUE TITLE
Remove regex and lazy_static dependency

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/descriptor-wallet#4]
Regex implies C library dependency, which makes crate portability complex. Lazy_static creates background thread, again complicating portability. Both dependencies does not deliver critical functionality and can be factored out.

**Comment by KaiWitt** [comment]
Hi, I like to work on this issue. 

Do I see correctly that the affected functions `SingleSig::from_str` and `DerivationComponents::from_str` have no test coverage?
