### ISSUE TITLE
Upgrade `rust-bitcoin` to `0.29.1`

### ISSUE THREAD

**Issue by ghost** [LNP-BP/descriptor-wallet#54]
The `FromSlip132` trait doesn't work with the latest version of `rust-bitcoin`. Is it possible to get a new release?

**Comment by dr-orlovsky** [comment]
Not yet possible - we need to wait for rust-miniscript with `0.29.1` support first

**Comment by andrewtoth** [comment]
It's possible now :) https://github.com/rust-bitcoin/rust-miniscript/commit/fd9ef55f894e9de2705822e801ac08cc563fc06a
