### ISSUE TITLE
Add BIP-88 support to PubkeyChain type

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/descriptor-wallet#8]

**Comment by cryptoquick** [comment]
There's no PubkeyChain type, but there's a value in `hd/src/derive.rs` that's called `pubkeychain` that's of the `TrackingAccount` type. Is this where BIP-88 support is needed? And what parts of [BIP-88](https://bips.dev/88/) are relevant?

**Comment by dr-orlovsky** [comment]
Yes, the `PubkeyChain` was renamed into `TrackingAccount`. That is where we need to support BIP-88
